### ISSUE TITLE
requestFile Function

### ISSUE THREAD

**Issue by dghelm** [NebulousLabs/skynet-js#129]
Currently, the SDK uses very similar ways of directing the browser to "download" or "open" files, both by calling the window object. 

As I work more with skynet-js, I'm wondering if "requesting" a file and returning the data of the Axios response (and perhaps skylink metadata) makes sense, especially for txt, json or other filetypes.

I'd propose `getFile` for this, but that overlaps with SkyDB function names, so perhaps `client.requestFile(skylink)`? 

I'd be happy to do the initial implementation.

**Comment by mrcnski** [comment]
Yeah, this is definitely something we want and that is needed for the ecosystem. `requestFile` sounds good. `downloadFile` should stay the same since we are guaranteeing backwards compatibility for the SDK since v2 (for everything except the SkyDB functions which are an explicitly unstable API).

> I'd be happy to do the initial implementation.

That would be great! 🙂 Let us know if you have any questions.
